stac-utils/qgis-stac-plugin

.github/workflows/release.yml, CHANGELOG.md, README.md, admin.py, pyproject.toml
Follow up fixes for https://github.com/stac-utils/qgis-stac-plugin/pull/8, includes update to the plugin releases workflow
=> Release fixes

.github/workflows/ci.yml, .github/workflows/release.yml, README.md
Follow up fix for https://github.com/stac-utils/qgis-stac-plugin/pull/8
=> Update on release docs, github actions naming and QGIS 3.22 image

src/qgis_stac/gui/connection_dialog.py, src/qgis_stac/gui/main.py, src/qgis_stac/ui/connection_dialog.ui, src/qgis_stac/ui/qgis_stac_widget.ui
=> Add connection dialog 

src/qgis_stac/conf.py, src/qgis_stac/definitions/catalog.py, src/qgis_stac/gui/main.py, src/qgis_stac/main.py, src/qgis_stac/utils.py
=> add list of populate stac api

src/qgis_stac/ui/qgis_stac_widget.ui
Tweaks on the search and settings tabs, now using [QgsCollapsibleGroupBox](https://qgis.org/api/classQgsCollapsibleGroupBox.html) instead of QGroupBox.
=> Updates in plugin main UI 

src/qgis_stac/conf.py
Changed the connection update signal to not send any string when emitted.
=> Updated connection signal signature

src/qgis_stac/gui/qgis_stac_widget.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/42
=> Resolve issue when searching for first time after installing the plugin

src/qgis_stac/api/models.py, src/qgis_stac/conf.py, src/qgis_stac/gui/qgis_stac_widget.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/43
Enables saving and restoring the search tab search filters values.
=> Feature for handling storing and retrieving search filters settings

src/qgis_stac/api/base.py, src/qgis_stac/api/client.py, src/qgis_stac/api/models.py, src/qgis_stac/api/network.py, src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/ui/qgis_stac_widget.ui
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/44
Updated pagination functionality now using the [ItemCollection](https://pystac-client.readthedocs.io/en/latest/api.html#pystac_client.ItemSearch.get_item_collections) generator to produce pagination for the search result items.
=> Updates on pagination functionality

src/qgis_stac/conf.py, test/test_settings_manager.py
=> Fix created_date in conf

src/qgis_stac/api/network.py, src/qgis_stac/gui/qgis_stac_widget.py
Fixed the pagination logic for determining total items and total pages that was making the item search slow.
=> Fix slow item search

src/qgis_stac/api/models.py, src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/gui/result_item_widget.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/52
Loads the items assets that are COGs https://www.cogeo.org/ into QGIS as map layers.
=> Add assets as layers into QGIS

.github/workflows/ci.yml
Updated tests to include image for the QGIS latest docker image.
=> Test update

src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/gui/result_item_delegate.py, src/qgis_stac/gui/result_item_widget.py, src/qgis_stac/ui/result_item_widget.ui
Updates on how the QTreeView on the results tab in populated with the search results item widget.
Follow up on https://github.com/stac-utils/qgis-stac-plugin/pull/58
=> Search result item widget update

src/qgis_stac/api/models.py, src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/gui/result_item_widget.py, src/qgis_stac/ui/qgis_stac_widget.ui, src/qgis_stac/utils.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/57,
Adds download support for STAC items assets
Screenshot
=> Support for downloading assets

README.md, docs/installation.md, poetry.lock
Follow up PR from https://github.com/stac-utils/qgis-stac-plugin/pull/56
=> Updates to the plugin documentation

src/qgis_stac/api/models.py, src/qgis_stac/conf.py, src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/ui/qgis_stac_widget.ui, src/qgis_stac/ui/result_item_widget.ui, test/test_settings_manager.py
Follow up from https://github.com/stac-utils/qgis-stac-plugin/pull/75
=> Plugin UI tweaks part II

src/qgis_stac/conf.py
Fixes a Nonetype error when installing the plugin for first time
screenshot of the error
=> Fix bug installing the plugin for first time

src/qgis_stac/gui/connection_dialog.py, src/qgis_stac/gui/qgis_stac_widget.py
Update API client details when current connection settings have changed.
=> API client updates

src/qgis_stac/api/base.py, src/qgis_stac/api/client.py, src/qgis_stac/api/models.py, src/qgis_stac/api/network.py, src/qgis_stac/conf.py, src/qgis_stac/gui/connection_dialog.py, src/qgis_stac/ui/connection_dialog.ui, src/qgis_stac/utils.py, test/test_settings_manager.py, test/test_stac_api_client.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/59
Update plugin to show the available API conformance classes in the connection dialog,  these classes indicate what operations a specific STAC API conforms to.
screenshot
=> Support conformance

src/qgis_stac/api/models.py, src/qgis_stac/conf.py, src/qgis_stac/gui/json_highlighter.py, src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/ui/qgis_stac_widget.ui
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/60
Reorganized the search UI tab to include an advanced filter group box that can be used to perform search with STAC query language and CQL-JSON filter language.
Screenshot
=> Query filter support

src/qgis_stac/api/base.py, src/qgis_stac/api/client.py, src/qgis_stac/api/network.py, src/qgis_stac/gui/result_item_widget.py
Updates on the approach for fetching the items after search in complete, now every api request is made in the content fetcher task.
=> Change items fetching flow

src/qgis_stac/api/base.py, src/qgis_stac/api/models.py, src/qgis_stac/api/network.py, src/qgis_stac/gui/connection_dialog.py, src/qgis_stac/ui/connection_dialog.ui
Added changes to enabled testing a connection if it is a valid STAC API. The test tries to retrieve a STAC item from a provided connection and if successfully fetch an item the connection will be considered valid, otherwise it will be an invalid connection.
=> Implemented test connection functionality

src/qgis_stac/conf.py, src/qgis_stac/gui/qgis_stac_widget.py
Resolves issues when loading filter settings and setup for the filter languages in the plugin.
=> Fix filter setup when loading plugin

.github/workflows/build-docs.yml, .github/workflows/build_docs.yml
Added a new workflow to enable manual build of the plugin documentation see https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch
=> Workflow for building documentation

.github/workflows/build-docs.yml
Follow up fix for https://github.com/stac-utils/qgis-stac-plugin/pull/96
=> Changed the admin file name

docs/installation.md
Updates on the installation documentation in the GitHub pages.
=> Installation documentation

src/qgis_stac/definitions/catalog.py, src/qgis_stac/main.py, src/qgis_stac/utils.py
Updated plugins and web menu entry to contain action to open documentation site.
Screeshot
=> Added documentation action menu entry

src/qgis_stac/gui/assets_dialog.py
Finished up support for QGIS vector layers assets including geojson and geopackage vector types.
=> Complete support for adding geojson and geopackage

src/qgis_stac/gui/assets_dialog.py, src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/ui/qgis_stac_widget.ui
Removed logic for highlighting filter text, resolving slow text input issue, also fixed downloading assets that have sas token issue.
=> Fix highlighting and asset download

docs/plugin/changelog.txt, pyproject.toml, src/qgis_stac/gui/qgis_stac_widget.py
Made changes to the change log, plugin tags and removed `CQL2-JSON` filter language.
=> Prepared changelog and tags for release

poetry.lock, pyproject.toml
Changed the plugin homepage, issue tracker and repository pages to the use the correct links.
=> Updated homepage, tracker and repository pages

docs/tutorial.md
Change the tutorial video url to use the embed one.
=> Update tutorial video URL

src/qgis_stac/api/models.py, src/qgis_stac/gui/assets_dialog.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/133
=> Support for loading netCDF assets

src/qgis_stac/lib/pystac/cache.py, src/qgis_stac/lib/pystac/catalog.py, src/qgis_stac/lib/pystac/collection.py, src/qgis_stac/lib/pystac/extensions/datacube.py, src/qgis_stac/lib/pystac/extensions/eo.py, src/qgis_stac/lib/pystac/extensions/file.py, src/qgis_stac/lib/pystac/extensions/hooks.py, src/qgis_stac/lib/pystac/extensions/item_assets.py, src/qgis_stac/lib/pystac/extensions/label.py, src/qgis_stac/lib/pystac/extensions/pointcloud.py, src/qgis_stac/lib/pystac/extensions/raster.py, src/qgis_stac/lib/pystac/extensions/scientific.py, src/qgis_stac/lib/pystac/extensions/table.py, src/qgis_stac/lib/pystac/extensions/version.py, src/qgis_stac/lib/pystac/item.py, src/qgis_stac/lib/pystac/layout.py, src/qgis_stac/lib/pystac/link.py, src/qgis_stac/lib/pystac/serialization/identify.py, src/qgis_stac/lib/pystac/stac_object.py, src/qgis_stac/lib/pystac/summaries.py, src/qgis_stac/lib/pystac/utils.py, src/qgis_stac/lib/pystac/validation/stac_validator.py, src/qgis_stac/lib/pystac/version.py
Fixes #114 by upgrading to the latest release of pystac.
=> Upgraded vendored pystac to v1.3.0

src/qgis_stac/api/models.py, src/qgis_stac/conf.py, src/qgis_stac/gui/asset_widget.py, src/qgis_stac/gui/assets_dialog.py, src/qgis_stac/gui/qgis_stac_widget.py
Removed the plugin `Settings` class from models file to the configuration file.
=> Moved location of the plugin settings name class

src/qgis_stac/api/base.py, src/qgis_stac/api/models.py, src/qgis_stac/api/network.py, src/qgis_stac/conf.py, src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/gui/result_item_widget.py, src/qgis_stac/jobs/token_manager.py, src/qgis_stac/ui/qgis_stac_widget.ui, test/test_settings_manager.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/143
Adds new token manager that will be responsible for handling auto refresh of the SAS based plugin connections.
User can set the refresh period frequency in the settings tab refresh time input.
=> Add SAS token manager

src/qgis_stac/api/network.py, src/qgis_stac/jobs/token_manager.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/144
Sets subscription key for SAS Token signing if it is avaialable as an environment variable in the system.
=> Include subscription key when signing SAS items

src/qgis_stac/gui/asset_widget.py, src/qgis_stac/gui/result_item_widget.py, src/qgis_stac/ui/asset_widget.ui, src/qgis_stac/ui/item_assets_widget.ui
These changes provide a fix for an issue when loading the stored assets into the assets dialog.
=> Fix bug in accessing saved item assets

src/qgis_stac/api/models.py, src/qgis_stac/gui/asset_widget.py, src/qgis_stac/gui/assets_dialog.py, src/qgis_stac/utils.py
This is a very quick & dirty patch to get basic COPC support in the STAC plugin.
Refs #166
=> Initial COPC support

src/qgis_stac/gui/qgis_stac_widget.py
Update on the SAS token refresh frequency.
=> Set default SAS token refresh period to 30 mins

src/qgis_stac/conf.py
Added missing documentation for some of the functions in the CollectionSettings class.
=> Add missing docs

src/qgis_stac/gui/assets_dialog.py, src/qgis_stac/ui/asset_widget.ui, src/qgis_stac/ui/item_assets_widget.ui
This PR contains changes for the fixing loading of the netCDF assets and some minor asset widget UI updates.
=> Fix for asset loading for netCDF type

src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/gui/result_item_widget.py, src/qgis_stac/ui/qgis_stac_widget.ui, src/qgis_stac/ui/result_item_widget.ui
Added support for loading multiple footprints at once.
Screenshot showing how the plugin supports adding multiple item footprints
=> Multiple loading of footprints

src/qgis_stac/utils.py
Updates to include sas subscription key when initializing defaults catalogs.
=> Small fix when starting up plugin after first install

src/qgis_stac/api/base.py, src/qgis_stac/api/client.py, src/qgis_stac/api/network.py, src/qgis_stac/conf.py, src/qgis_stac/gui/collection_dialog.py, src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/ui/collection_dialog.ui
Due to the long time taken to fetch catalog collections, we are updating the workflow to only fetch few information about the collection and re-fetch additional details when users loads a collection dialog for a respective collection.
Screenshot of how collections fetch will be as suggested in this PR.
=> Updates to workflow in getting collections.

src/qgis_stac/gui/assets_dialog.py
Import gdal package from osgeo.
=> Update import of gdal

src/qgis_stac/utils.py
Follow up on https://github.com/stac-utils/qgis-stac-plugin/pull/188.
=> Update import of gdal in utils

.github/workflows/ci.yml
Update CI test images to match recent released QGIS docker images.
=> Update CI test images

src/qgis_stac/gui/qgis_stac_widget.py, src/qgis_stac/ui/qgis_stac_main.ui
Enables addition of the all the current page items footprint at once, each footprint is added as a separate layer.
Screenshot
=> Support for adding all footprints at once

src/qgis_stac/api/models.py, src/qgis_stac/gui/qgis_stac_widget.py
Updates to footprints addition workflow and fix for https://github.com/stac-utils/qgis-stac-plugin/issues/197
=> Minor updates

src/qgis_stac/gui/qgis_stac_widget.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/208
Updates the processing feedback progress value, casting it from float to integer.
=> Change progress value type

README.md
Update the badge url to follow the recent changes from here https://github.com/badges/shields/issues/8671
=> Change build badge

test/mock/stac_api_auth_server_app.py, test/test_stac_api_client_auth.py
Follow up changes from https://github.com/stac-utils/qgis-stac-plugin/pull/233 which caused tests to fail in the main branch merge commit, more info https://github.com/stac-utils/qgis-stac-plugin/actions/runs/8725554192/job/23938791044.
=> Fix main branch failing tests

docs/plugin/changelog.txt
Includes the missing changelog text in the plugin main changelog file.
=> Update changelog document

docs/plugin/changelog.txt, pyproject.toml
Changes for preparing plugin version 1.1.2 release
=> Changelog for version 1.1.2 
