stac-utils/qgis-stac-plugin

- .github/workflows/ci.yml
Removed testing on QGIS latest docker images, as they are not available at the moment.
> Updates on tests

- src/qgis_stac/conf.py
- src/qgis_stac/gui/connection_dialog.py
- src/qgis_stac/gui/main.py
- src/qgis_stac/ui/qgis_stac_widget.ui
- src/qgis_stac/utils.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/30
Adds functionality to handle connections edit and removal. Now edits on connection name will update the same connection and any new connection with a name that matches some available connection then the new connection name will be tagged with a no suffix; eg "name" will be "name(1)"
When removing a connection we are setting the most recent added connection as the current connection on the connections combo box.
screenshot showing the edit and remove buttons in action
> Implemented edit and remove functions for connections

- admin.py
- src/qgis_stac/api/base.py
- src/qgis_stac/api/client.py
- src/qgis_stac/api/models.py
- src/qgis_stac/api/network.py
- src/qgis_stac/definitions/catalog.py
- src/qgis_stac/gui/connection_dialog.py
- src/qgis_stac/gui/main.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/gui/result_item_delegate.py
- src/qgis_stac/gui/result_item_model.py
- src/qgis_stac/gui/result_item_widget.py
- src/qgis_stac/main.py
- src/qgis_stac/ui/qgis_stac_widget.ui
- src/qgis_stac/ui/result_item_widget.ui
- src/qgis_stac/utils.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/21, https://github.com/stac-utils/qgis-stac-plugin/issues/22 and https://github.com/stac-utils/qgis-stac-plugin/issues/31
Adds search logic in the plugin, now collections can be used when searching, results are shown using the search item result widget template.
Searching items current workflow
Remaining issues
> Implement search

- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/gui/result_item_model.py
- src/qgis_stac/ui/qgis_stac_widget.ui
Follow up, updates from https://github.com/stac-utils/qgis-stac-plugin/pull/40
> Added filter and sorting functionalities to the searched items

- src/qgis_stac/api/models.py
- src/qgis_stac/api/network.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/gui/result_item_widget.py
- src/qgis_stac/ui/qgis_stac_widget.ui
Update the results tab to use QScrollArea instead of QTreeView that used a delegate to render search item results and caused QGIS to crash when painting pixmap.
Now user can search and see results with thumbnail and load the COG item assets into QGIS.
Screenshot
> Fix when adding layers and thumbnails

- src/qgis_stac/lib/typing/LICENSE
- src/qgis_stac/lib/typing_extensions.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/41
Includes the missing typing_extensions library for the QGIS version that don't have it.
> Add typing_extensions library

- src/qgis_stac/api/client.py
- src/qgis_stac/api/models.py
- src/qgis_stac/gui/result_item_widget.py
- src/qgis_stac/ui/qgis_stac_widget.ui
- src/qgis_stac/ui/result_item_widget.ui
Follow up PR from https://github.com/stac-utils/qgis-stac-plugin/pull/68
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/57
Enables loading item footprints inside QGIS as map layers.
Screenshot
> Support for loading item footprints when they are available

- src/qgis_stac/api/client.py
- src/qgis_stac/api/network.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/ui/qgis_stac_widget.ui
Updates and fixes on the plugin UI, including
cc @mmcfarland
> Plugin UI tweaks

- src/qgis_stac/utils.py
When setting the default STAC APIs we now config them with empty collections.
Screenshot
> Initialize default connections with empty collections

- src/qgis_stac/conf.py
- src/qgis_stac/definitions/catalog.py
- src/qgis_stac/utils.py
Follow up PR from https://github.com/stac-utils/qgis-stac-plugin/pull/79
Added  and set value for the capability property for each of the auto configured plugin connections.
These connections are created when installing the plugin for the first time, see https://github.com/stac-utils/qgis-stac-plugin/pull/26
> Set capabilities for plugin default connections

- src/qgis_stac/gui/qgis_stac_widget.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/69
Adds the UI filter and sort functionality for the search results items, using [QSortFilterProxyModel ](https://doc.qt.io/qt-5/qsortfilterproxymodel.html) API and updating the view with the resulting data from the proxy model.
> Implemented filter and sort for search item results

- src/qgis_stac/api/client.py
- src/qgis_stac/api/network.py
- src/qgis_stac/gui/qgis_stac_widget.py
When fetching collections, we should be returning list of collections from the network content fetcher to the plugin UI, and not a Collection generator.
We need to also make sure we prepare the collection list in a the background task as each iteration inside the Collection generator makes a network request to the API.
> Update content fetcher logic when fetching collections

- src/qgis_stac/api/client.py
- src/qgis_stac/api/models.py
- src/qgis_stac/api/network.py
- src/qgis_stac/gui/result_item_widget.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/74
Uses the API pystac Item as a footprint instead of adding its geometry only.
Screenshot
cc @mmcfarland
> Load the whole STAC item as a footprint

- src/qgis_stac/api/network.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/73
Some of the STAC item assets dont have a title, we are defaulting to use their dictionary key as the asset title.
> Fallback to asset key if asset title is not available

- src/qgis_stac/gui/connection_dialog.py
- src/qgis_stac/ui/qgis_stac_widget.ui
Updated the connection invalid connection message level to critical when testing connections and removed load and save connections buttons.
> Update message level and removed unused connection buttons

- src/qgis_stac/gui/asset_widget.py
- src/qgis_stac/gui/assets_dialog.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/gui/result_item_widget.py
- src/qgis_stac/main.py
- src/qgis_stac/ui/asset_widget.ui
- src/qgis_stac/ui/item_assets_widget.ui
- src/qgis_stac/ui/qgis_stac_widget.ui
- src/qgis_stac/ui/result_item_widget.ui
Reorganized the way item assets are downloaded and loaded into QGIS.
These changes contain modification to main plugin widget to subclass a QDialog instead of QWidget so as to make it modal, blocking input from other application widgets.
Screenshot
> Assets download and loading updates

- src/qgis_stac/conf.py
- src/qgis_stac/gui/qgis_stac_widget.py
After the get collections activity finishes a UI lag appears on the plugin search tab input widgets, this was because of the 
save filter operation that was saving the collections into the plugin settings each time any on the inputs widget were altered.
This PR updates the collections save function to only operate once the collections have been fetched.
Old behaviour
New behaviour
> Fix for UI lag after fetching collections

- src/qgis_stac/gui/qgis_stac_widget.py
I have been testing this plugin and connecting to a STAC server where the collections haven't been given titles. Currently each of these collections displays in the collections list as `No Title`. This PR updates this so that any collections without a title are displayed as `No Title (collection_id)` - for example `No Title (test-collection)`, so that they can be distinguished.
> Change collections list to display collection ID in brackets if no title

- test/mock/mock_http_server.py
- test/test_stac_api_client.py
Updates the logic in shutting down the mock server for testing, the past approach was causing the CI to hold when running the tests on environments that contains latest `Wezkzeug` package.
Now using `Process` class to handle server start and termination as the `werkzeug.server.shutdown` is deprecated in Werkzeug 2.0. see https://github.com/pallets/werkzeug/issues/1752 and https://werkzeug.palletsprojects.com/en/2.1.x/serving/#shutting-down-the-server
> Change in tests mock app server

- src/qgis_stac/gui/connection_dialog.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/122
Changes connection dialog title to "Edit Connection" when in editing mode and updates connection dialog inputs to be disabled when fetching conformance classes.
> Updates on the connection dialog

- src/qgis_stac/definitions/constants.py
- src/qgis_stac/gui/result_item_widget.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/125
Use overview asset as a thumbnail if an item doesn't have a thumbnail asset, and when fetching the overview append height and width url params to get a thumbnail like size.
> Thumbnail update

- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/ui/qgis_stac_widget.ui
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/131
Adds a label that will be used to display current selected collections from the collection list.
screenshot showing how the selected collections will be displayed
> Show selected collections

- src/qgis_stac/api/models.py
- src/qgis_stac/gui/qgis_stac_widget.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/128
Updated the filter languages that can be used in the plugin, now the plugin supports CQL2 JSON usage.
Screenshot of the plugin search using CQL2 JSON language
> Support CQL2 JSON

- src/qgis_stac/api/models.py
- src/qgis_stac/api/network.py
- src/qgis_stac/conf.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/gui/result_item_model.py
- src/qgis_stac/ui/qgis_stac_widget.ui
- test/test_stac_api_client.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/127
These changes relocate the sort and ordering buttons from the result tab to the search tab, from now on the sorting will be done per search results items and not per search results items page.
The result items proxy model only contain the filtering capability as the sorting now has been moved to be done by the STAC API.
Screenshot of the new location of the sort buttons
> Move sort and order buttons into the search tab

- src/qgis_stac/gui/qgis_stac_widget.py
Show the selected collections label all the time, to avoid UI shift when the label is shown.
> Main UI update

- src/qgis_stac/api/models.py
- src/qgis_stac/api/network.py
- src/qgis_stac/conf.py
- src/qgis_stac/gui/collection_dialog.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/ui/collection_dialog.ui
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/126
Created a new dialog for showing STAC collection information. Currently the all the catalog collections informations are stored in the plugin when fetching the catalog collections. This dialog will be used to show user the fetched collection details.
Double cliking a collection item in the collections list will open Collection dialog for the clicked collection.
When fetching the collection we now store extra collection properties including collection extent, links, providers, description, license, keywords and STAC version.
If the catalog collections spatial extent doesn't have `bbox` property as required in (https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#spatial-extent-object) we …
> Implement dialog for showing STAC collection details

- src/qgis_stac/gui/asset_widget.py
- src/qgis_stac/gui/assets_dialog.py
- src/qgis_stac/gui/qgis_stac_widget.py
These changes contain fix for issues when downloading item assets that have filenames with invalid characters, updates that enables progress bar to show progress value when downloading  the item assets and when the download folder is not set the plugin will use a system temporary folder as a download destination( see https://api.qgis.org/api/classQgsProcessing.html#a62584b5ed1558ebdf04a95d6f4a9d403)
Screenshot showing how download progress will be shown
> Fix file download

- src/qgis_stac/gui/qgis_stac_widget.py
When a new STAC catalog connection has been created refresh the current list of collections to remove the collections for the past active connection.
> Refresh collection list view when new connection has been added

- src/qgis_stac/ui/collection_dialog.ui
The pystac library currently doesn't expose the Collection STAC version. This change removes the STAC version label and value from the collection dialog `Identification` tab.
> Remove the STAC version label from collection dialog

- test/test_stac_api_client.py
After updating the pystac library in the plugin, these changes add the STAC collection tests running on a localhost mock STAC API server.
> Add tests for STAC collections.

- test/test_stac_api_client.py
Remove redudant checks for the conformance fetching in the plugin tests.
> Move conformance tests into one block

- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/ui/qgis_stac_widget.ui
When searching is in process we need to disable the sort buttons and enable them once search has finished.
> Disable the sort buttons when searching the catalogs

- src/qgis_stac/conf.py
- src/qgis_stac/gui/asset_widget.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/ui/asset_widget.ui
- src/qgis_stac/ui/qgis_stac_widget.ui
These changes include a new added setting in the plugin settings table that helps users to specify whether to load an asset after downloading it.
Screenshot of the settings tab UI including the new setting.
> New asset loading setting

- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/ui/qgis_stac_widget.ui
Updates to the search tab date filter, spatial extent and advance group boxes. When the plugin is opened on the first time after install these groups should be collapsed.
> Minor UI updates to the search tab

- src/qgis_stac/gui/qgis_stac_widget.py
These changes makes sure that the collection model is cleared out before populating the collection view with another list of the STAC collections.
> Remove duplicate collections entries.

- src/qgis_stac/gui/asset_widget.py
- src/qgis_stac/gui/assets_dialog.py
This PR contains changes in the layer type check when loading asset as a layer in map canvas.
> Update layer types check when loading assets into QGIS 

- src/qgis_stac/api/models.py
- src/qgis_stac/api/network.py
- src/qgis_stac/conf.py
- src/qgis_stac/gui/result_item_widget.py
- src/qgis_stac/ui/result_item_widget.ui
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/129
Updates the labels of the result item widget, including the eo:cloud_cover property and collection name if the the collection for the item has already been fetched by the plugin.
New look of the result items widgets
> Result item UI update

- src/qgis_stac/gui/asset_widget.py
- src/qgis_stac/gui/assets_dialog.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/main.py
- src/qgis_stac/ui/asset_widget.ui
- src/qgis_stac/ui/item_assets_widget.ui
Implemented the support for multiple loading of assets as layers and assets downloading.
These changes also contain updates that include the minimize and maximize button in plugin main widget.
Screenshot of the multiple assets loading
> Support multiple assets loading and downloading

- src/qgis_stac/api/base.py
- src/qgis_stac/api/client.py
- src/qgis_stac/api/models.py
- src/qgis_stac/api/network.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/gui/queryable_property.py
- src/qgis_stac/main.py
- src/qgis_stac/ui/qgis_stac_widget.ui
- src/qgis_stac/ui/queryable_property.ui
These changes contain support for using STAC queryables properties for filtering in the plugin.
The queryables are fetched based on thei definition in https://github.com/radiantearth/stac-api-spec/blob/master/fragments/filter/README.md#queryables.
Currently the pystac-client library does not have an API for getting the queryable properties see https://github.com/stac-utils/pystac-client/issues/231, so this implementation doesn't use the pystac-client API instead we have added a new class `NetworkFetcher` that will be responsible for fetching all the resources that cannot be fetched via the pystac-client library.
The plugin search tab now contains a new group box `Data driven queryables` that is responsible for fetching and setting values for the queryable properties.
Data drive queryables …
> Add support for queryables filtering

- src/qgis_stac/api/network.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/main.py
- src/qgis_stac/ui/qgis_stac_widget.ui
When fetching for queryable properties make sure we clear the current ones before adding new fetched properties.
> Clear queryable properties when refetching them

- src/qgis_stac/api/network.py
- src/qgis_stac/gui/assets_dialog.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/ui/qgis_stac_widget.ui
These updates removes search results items signing and now the SAS token signing will only be applied to the items assets when loading or downloading the respective assets.
Also this PR disable auto-signing of items as from now on all items assets will be getting new token each time their are being loaded or downloaded.
> Remove search results items signing for SAS based connections.

- src/qgis_stac/api/network.py
- src/qgis_stac/gui/assets_dialog.py
- src/qgis_stac/gui/qgis_stac_widget.py
- src/qgis_stac/main.py
- src/qgis_stac/ui/qgis_stac_main.ui
When loading and downloading assets if the operation is successful and unrelated error occurs afterwards we should only log the error in the plugin log. Also these changes contain updates to the pluign main UI now using QMainWindow as a base class for the plugin main widget.
> UI minor updates

- src/qgis_stac/api/models.py
- src/qgis_stac/gui/asset_widget.py
- src/qgis_stac/gui/assets_dialog.py
- src/qgis_stac/gui/result_item_widget.py
- src/qgis_stac/utils.py
This PR contains changes that provide a fix for a current bug in loading NETCDF assets layers. The changes contain a total overhaul of the approach in adding NETCDF assets as QGIS map layers.
The new approach is to first download the NETCDF asset and the use the GDAL package to read the available NETCDF variables and then add all the sublayers from the found variables.
The NETCDF asset type is the only type that will require to be downloaded first in order to be loaded as a layer, this is because before adding the NETCDF type we need prior details about the available variables which can only be fetch if the asset has already been downloaded.
The changes also update workflow in checking if the plugin has finished downloading the assets, instead of checking the progress value of the …
> Fix for NETCDF assets loading

- src/qgis_stac/gui/qgis_stac_widget.py
Now checking for both `toggled` and `stateChanged` Qt checkbox signal when user change the assets loading when downloading setting.
> Update signal connection to assets loading settings

- src/qgis_stac/gui/qgis_stac_widget.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/200
When new search has finished we need to clear the past selected footprints.
> Clear selected footrpints when new search has finished

- src/qgis_stac/gui/connection_dialog.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/210
Adds the missing variable when creating a connection from the connection dialog inputs.
> Fix for error when testing a new connection

- src/qgis_stac/main.py
Fixes https://github.com/stac-utils/qgis-stac-plugin/issues/209
Deletes the plugin menu entry on the plugin web menu.
> Remove plugin web menu entry when plugin is uninstalled

- src/qgis_stac/api/network.py
When fetching collections from API we need to relay feedback to user after getting exceptions based on [pystac errors](https://pystac.readthedocs.io/en/stable/api/errors.html).
> Handle STACTypeError from pystac

- src/qgis_stac/api/network.py
Fix for #234
This PR contains a change that fixes collection information dialog error that was happening when the collection information dialog for a collection that doesn't contain providers details is opened.
It has been mentioned in https://github.com/radiantearth/stac-api-spec/blob/master/stac-spec/collection-spec/collection-spec.md#collection-fields, `providers` field is not a required field and the STAC collection may not contain them.
Before fix
After fix
> Fix collection information dialog 

- src/qgis_stac/gui/asset_widget.py
Fix for https://github.com/stac-utils/qgis-stac-plugin/issues/227
These changes add functionality to check for the asset type from the provided asset href when the corresponding STAC item asset doesn't contain media type.
> Resolve asset type error

- .github/workflows/build-docs.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
Adds recent QGIS versions to run the plugin CI tests against. Currrent QGIS LTR version is on 3.34, for more info https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release
> Updates on the CI workflows

- src/qgis_stac/gui/assets_dialog.py
Updates the assets dialog title instead of displaying the length of the item id to show the exact item id when the item assets are empty.
> Fix item assets dialog title
